#Mysql:
host: localhost
port: 3306
database: shops
username: root
password: password

unclaimedName: "&c&lUnclaimed lot"
unclaimedLore:
  - ""
  - "&7Purchase this lot to"
  - "&7Create your personal shop"
  - ""
  - "&c&lId: &7{id}"
  - "&c&lCost: &7{price}"
  - "&7&o(( Right-Click to purchase ))"
claimedName: "&c&l{name}"
claimedLore:
    - ""
    - "&c&lOwner&7: {player}"
    - "&c&lId&7: {id}"
    - "&c&lDescription: {description}"
    - ""
    - "&7&o(( Right-Click to warp ))"
    -

#MYSQL information:
host: 'localhost'
port: '3306'
database: 'shops'
username: 'root'
password: 'password'